# Generated by Django 3.2.4 on 2021-06-19 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='Reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
